### ISSUE TITLE
Weird error message "I'm sorry, but your not authorized to install Slackfish"

### ISSUE THREAD

**Issue by micuintus** [neversun/Slackfish#26]
Dear Robert,

First of all, thanks a lot for providing this Slack app for Sailfish!
Unfortunately, when I try logging with Slackfish to my company's channel,
I get a weird error message:  "I'm sorry, but your not authorized to install Slackfish".

![20161204173406](https://cloud.githubusercontent.com/assets/8768660/20867653/024ab0fc-ba4a-11e6-8dff-9cbd0b6bccd4.jpg)

I contacted our company's Slack admin team. They told me 
that they do "not actively block the mentioned app. We only
use the environment Slack itself is providing." Furthermore,
they told me that there was no "Slackfish" app they could integrate.

Do you have any idea what the problem is and how I could solve it?
Having a native Slack client on my Jolla, which I can use, 
would be really awesome!

Best, 
micu

**Comment by neversun** [comment]
Hey micu, I will look into this. But this version is pre-alpha. As an end user you should wait for a regular (beta) release.
Until then you could use the Slackfish app (same name, but different code/author) out of Jolla store. It is in a more ready-to-use state.

**Comment by neversun** [comment]
Hey @micuintus,
this happens because your admins enables this setting:
![image](https://cloud.githubusercontent.com/assets/9157500/21080525/8a6dfedc-bfb1-11e6-8275-5ba8dbaa5a35.png)

Second your admins cannot find this app in the directory, because it is not yet approved by Slack. This is because project status is not even alpha.

But your admins could try this link [https://slack.com/apps/A0EHSABB8-slackfish](https://slack.com/apps/A0EHSABB8-slackfish) and should be able to approve it.
But as I said: **This is not enduser ready!**

Greetings.

**Comment by micuintus** [comment]
Hi @neversun,

Thanks a lot for your help!
And sorry for not getting back earlier, because this is quite embarrassing. You probably might have already guessed it: It turns out that I mixed up your app with the one on the harbour store. :|


Assuming there is only one such app, I just googled "Slackfish" — and consequently also assumed that the Github site I found actually belongs to the app I downloaded from store. I am very sorry.

But you might have helped me nevertheless and apart from that now I know that there is another "Slackfish" app I can try out (in the future). :)

Sorry again!
Cheers,
micu

**Comment by neversun** [comment]
Glad to help :)

I may rename this app due to the github-wise newer, but as `Slackfish` released other slack app.

**Comment by micuintus** [comment]
Can you tell me where this ```A0EHSABB8-slackfish``` id comes from?

**Comment by neversun** [comment]
As the creator of that slack integration I can see this linke somewhere in Slack's app creator space.
